AWSTemplateFormatVersion : '2010-09-09'

Parameters:
  bucketName: 
    Type: String

Description: my template
Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref bucketName


Outputs:
  OuputValue1:
    Value: !Ref MyBucket